### PR TITLE
fix: `lint-staged` better config

### LINKED ISSUE #48: Fix `lint-staged` config to only check staged files

### PR DESCRIPTION
**Pull request by daanvosdewael**
Fixes  #48

- callback functie toegevoegd om alleen staged files te linten
- regex aanpassingen voor `ignorePatterns` en `eslint` script voor betere matching van dot files en folders

### CODE REVIEW

File: .lintstagedrc.mjs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export default {
+    '**/*.?(m)js': filenames => `eslint ${filenames.join(' ')} --fix`,
```
Comment (jochemkeller) [inline .lintstagedrc.mjs:2]: I was debating whether I like the addition of `--fix` here 🤔 feels like it should be the developers responsibility if a commit passed through linting, as opposed to this where it automagically fixes it and the commit goes through if only autofixable errors / warnings are found. Hurts the discoverability a bit? But, not a blocker I guess 🤷

**Review by jochemkeller — APPROVED** [review]
